name: Validate

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-hassfest:
    name: Hassfest validation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: home-assistant/actions/hassfest@master

  validate-hacs:
    name: HACS validation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: hacs/action@main
        with:
          category: integration
